export enum ActionEnum {
  MESSAGE_LIST_REQUEST = 'MESSAGE_LIST_REQUEST',
  MESSAGE_LIST_UPDATE = 'MESSAGE_LIST_UPDATE',

  PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST',
  PRODUCT_LIST_UPDATE = 'PRODUCT_LIST_UPDATE',

  AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST',
  AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST'
}
